### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by prokoudine** [timowest/flute-lv2#1]
$ make
lv2peg flute.ttl gen/Flute.peg
python portmeta.py
Traceback (most recent call last):
  File "portmeta.py", line 62, in <module>
    cppFile = open("gen/FluteMeta.h", "w")
IOError: [Errno 2] No such file or directory: 'gen/FluteMeta.h'
make: **\* [gen/FluteMeta.h] Error 1

Looks like a file that wasn't added to repo :)

**Comment by timowest** [comment]
Sorry for the issues. I just fixed the Makefile. My output looks now like this : 

tiwe@tiwe-laptop:~/work/lv2/flute-lv2$ make clean && make
rm -rf lv2-Flute.lv2 _.so *.out *.wav gen/_ alsa-gtk 
mkdir gen
lv2peg flute.ttl gen/Flute.peg
python portmeta.py
faust -a minimal.cpp faust/flute.dsp > gen/dsp.cpp
g++ -shared -Wall -fPIC -DPIC Flute.cpp dsp.cpp `pkg-config --cflags --libs paq` -lm -I/usr/local/lib/faust/ -o Flute.so
g++ -shared -Wall -fPIC -DPIC FluteGUI.cpp `pkg-config --cflags --libs paq` `pkg-config --cflags --libs gtkmm-2.4` -o FluteGUI.so
rm -rf lv2-Flute.lv2
mkdir lv2-Flute.lv2
cp manifest.ttl flute.ttl Flute.so FluteGUI.so lv2-Flute.lv2

**Comment by prokoudine** [comment]
Thanks!

I pulled the changes, but unfortunately it's still broken for me:

$ make
lv2peg flute.ttl gen/Flute.peg
python portmeta.py
faust -a minimal.cpp faust/flute.dsp > gen/dsp.cpp
undefined symbol BoxIdent[midikey2hz]
????: -1: ERROR: undefined symbol  BoxIdent[midikey2hz]
make: **\* [gen/dsp.cpp] Error 1

Do I need a specific version of Faust? Mine is 0.9.24.

**Comment by timowest** [comment]
Yes, please use the Faust 2 branch.

You can switch it like this when using Git :

  git checkout -b faust2 origin/faust2
  make && sudo make install
